raw = "data/raw"
processed_dir = "data/processed"
input = "_chat.txt"
current = "whatsapp-20250408-164953-processed.parquet"
input_path = "whatsapp-20250408-152520.csv"
datetime_format = "%d/%m/%Y, %H:%M:%S"
img_folder = "img/"
author_info_path = "author_info.txt"
anon_reference = "anon_reference.json"